version: "2.3"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "127.0.0.1:5600:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./internal/njudge/db/migrations/1_init.up.sql:/docker-entrypoint-initdb.d/create_tables.sql
  web:
    image: njudge-web
    ports:
      - 5555:5555
    env_file:
      - web.env
    volumes:
      - type: bind
        source: ./njudge_problems
        target: /njudge_problems
    networks:
      - default
  judge:
    image: njudge-judge
    ports:
      - 8080:8080
    privileged: true
    cgroup: host
    env_file:
      - judge.env
    volumes:
      - type: bind
        source: ./njudge_problems
        target: /njudge_problems
      - type: bind
        source: /run/isolate/
        target: /run/isolate/
    networks:
      - default
  glue:
    image: njudge-glue
    env_file:
      - glue.env
    networks:
      - default
volumes:
  db:
    driver: local
  problems:
    driver: local
networks:
  default:
