version: "2.3"
services:
  base:
    image: ${COMPOSE_PROJECT_NAME}-base
    build: .
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "127.0.0.1:5600:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./internal/migrations/1_init.up.sql:/docker-entrypoint-initdb.d/create_tables.sql
  web:
    build:
      context: .
      args:
        - PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      dockerfile: internal/web/Dockerfile
    ports:
      - 5555:5555
    env_file:
      - web.env
    volumes:
      - type: volume
        source: problems
        target: /njudge_problems
    networks:
      - default
  judge:
    privileged: true
    build:
      context: .
      args:
        - PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      dockerfile: internal/judge/Dockerfile
    env_file:
      - judge.env
    volumes:
      - type: volume
        source: problems
        target: /njudge_problems
    networks:
      - default
  glue:
    build:
      context: .
      args:
        - PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      dockerfile: internal/glue/Dockerfile
    env_file:
      - glue.env
    networks:
      - default
volumes:
  db:
    driver: local
  problems:
    driver: local
networks:
  default:
