services:
  base:
    build: .
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5600:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations/1_init.up.sql:/docker-entrypoint-initdb.d/create_tables.sql
  web:
    build:
      context: .
      dockerfile: pkg/web/Dockerfile
    ports:
      - 5555:5555
    env_file:
      - web.env
    depends_on:
      - base
      - db
    volumes:
      - problems:/njudge_problems
    networks:
      - default
  judge:
    privileged: true
    build:
      context: .
      dockerfile: pkg/judge/Dockerfile
    env_file:
      - judge.env
    depends_on:
      - base
    volumes:
      - problems:/njudge_problems
      - logs:/njudge_logs
    networks:
      - default
  glue:
    build:
      context: .
      dockerfile: pkg/glue/Dockerfile
    env_file:
      - glue.env
    depends_on:
      - base
      - db
    networks:
      - default
volumes:
  db:
    driver: local
  problems:
    driver: local
  submissions:
    driver: local
  logs:
    driver: local
networks:
  default:
    name: njudge_default