output="internal/njudge/db/models"
wipe=true
no-context=false
no-tests=true
add-global-variants=true
[psql]
  dbname = "postgres"
  host   = "localhost"
  port   = 5600
  user   = "postgres"
  pass   = "postgres"
  schema = "public"
  sslmode = "disable"
  blacklist = ["schema_migrations", "http_sessions"]
