output="internal/web/models"
wipe=true
no-context=true
no-tests=true
add-global-variants=true
[psql]
  dbname = "njudge"
  host   = "localhost"
  port   = 5600
  user   = "postgres"
  pass   = "postgres"
  schema = "public"
  sslmode = "disable"
  blacklist = ["schema_migrations", "http_sessions"]
